[package]
name = "system"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
raw-cpuid = "11.5.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
status = { path = "../status" }
sys-info = "0.9.1"
wmi = "0.15.1"
