//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::battery_one_minutes::Entity as BatteryOneMinutes;
pub use super::battery_realtime::Entity as BatteryRealtime;
pub use super::battery_state_history::Entity as BatteryStateHistory;
pub use super::memory_battery_status::Entity as MemoryBatteryStatus;
