[package]
name = "battery"
version = "0.1.0"
edition = "2024"

[dependencies]
battery_lib = { package = "battery", version = "0.7" }
chrono = "0.4.40"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
status = { path = "../status" }
[dev-dependencies]
json = "*"
