[package]
name = "store"
version = "0.1.0"
edition = "2024"

[dependencies]
polars = { version = "^0.46", features = [
    "parquet",
    "lazy",
    "dynamic_group_by",
] }
chrono = "0.4.40"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
