[package]
name = "power"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
status = { path = "../status" }
libapuadj = { git = "https://github.com/topabomb/libapuadj", branch = "master" }

